/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.registrodepessoas;

import java.util.ArrayList;
import javax.swing.JOptionPane;


/**
 *
 * @author joaod
 */
public class LoginFrame extends javax.swing.JFrame {
    Conexao cnx=new Conexao();
    ArrayList<String> usuarios;
    ArrayList<String> senhas;
    
    /**
     * Creates new form login
     */
    public LoginFrame() {
        initComponents();
        carregarUsuariosSenhas();
    }
    private void carregarUsuariosSenhas(){
        usuarios=cnx.filtrar("SELECT usuario FROM administradores");
        senhas=cnx.filtrar("SELECT senha FROM administradores");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        usuarioEntry = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        senhaEntry = new javax.swing.JPasswordField();
        jPanel6 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(850, 650));

        jPanel1.setBackground(new java.awt.Color(74, 131, 150));
        jPanel1.setPreferredSize(new java.awt.Dimension(420, 0));

        jPanel3.setBackground(new java.awt.Color(74, 131, 150));
        jPanel3.setPreferredSize(new java.awt.Dimension(420, 160));

        jLabel1.setFont(new java.awt.Font("Calibri Light", 0, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Login");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(149, 149, 149)
                .addComponent(jLabel1)
                .addContainerGap(167, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel1)
                .addContainerGap(79, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel3);

        jPanel4.setBackground(new java.awt.Color(74, 131, 150));
        jPanel4.setPreferredSize(new java.awt.Dimension(420, 100));

        jPanel7.setBackground(new java.awt.Color(74, 131, 150));
        jPanel7.setPreferredSize(new java.awt.Dimension(360, 53));
        jPanel7.setLayout(new java.awt.BorderLayout(4, 4));

        usuarioEntry.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usuarioEntryActionPerformed(evt);
            }
        });
        jPanel7.add(usuarioEntry, java.awt.BorderLayout.CENTER);

        jLabel2.setFont(new java.awt.Font("Calibri Light", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Usuario");
        jPanel7.add(jLabel2, java.awt.BorderLayout.PAGE_START);

        jPanel4.add(jPanel7);

        jPanel1.add(jPanel4);

        jPanel5.setBackground(new java.awt.Color(74, 131, 150));
        jPanel5.setPreferredSize(new java.awt.Dimension(420, 100));

        jPanel8.setBackground(new java.awt.Color(74, 131, 150));
        jPanel8.setPreferredSize(new java.awt.Dimension(360, 53));
        jPanel8.setLayout(new java.awt.BorderLayout(4, 4));

        jLabel3.setFont(new java.awt.Font("Calibri Light", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Senha");
        jPanel8.add(jLabel3, java.awt.BorderLayout.PAGE_START);
        jPanel8.add(senhaEntry, java.awt.BorderLayout.CENTER);

        jPanel5.add(jPanel8);

        jPanel1.add(jPanel5);

        jPanel6.setBackground(new java.awt.Color(74, 131, 150));
        jPanel6.setFont(new java.awt.Font("Calibri Light", 0, 12)); // NOI18N
        jPanel6.setPreferredSize(new java.awt.Dimension(420, 120));

        jButton1.setBackground(new java.awt.Color(111, 167, 187));
        jButton1.setFont(new java.awt.Font("Calibri Light", 0, 24)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Entrar");
        jButton1.setAlignmentY(0.0F);
        jButton1.setMargin(new java.awt.Insets(3, 14, 2, 14));
        jButton1.setPreferredSize(new java.awt.Dimension(120, 60));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel6.add(jButton1);

        jPanel1.add(jPanel6);

        getContentPane().add(jPanel1, java.awt.BorderLayout.WEST);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setPreferredSize(new java.awt.Dimension(430, 508));
        jPanel2.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 5, 200));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resgistro.jpg"))); // NOI18N
        jPanel2.add(jLabel4);

        getContentPane().add(jPanel2, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void usuarioEntryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usuarioEntryActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_usuarioEntryActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        boolean dadosCorretos=false;
        String usuario=usuarioEntry.getText();
        String senha= new String(senhaEntry.getPassword());
        for(int i =0;i<usuarios.size();i++){
            if(usuario.equals(usuarios.get(i))){
                if(senha.equals(senhas.get(i))){
                    dadosCorretos=true;
                    RegistroDePessoas.setUsuario(usuarioEntry.getText());
                    senhaEntry.setText("");
                    usuarioEntry.setText("");
                }
                
            }
        }
        if(dadosCorretos){
            java.awt.EventQueue.invokeLater(new Runnable() {
                public void run() {
                    new RegistrosFrame().setVisible(true);
                }
            });
            this.dispose();
            JOptionPane.showMessageDialog(this, "Login feito!\nAguarde um pouco", "Aguarde", JOptionPane.INFORMATION_MESSAGE);
        }
        else{
            JOptionPane.showMessageDialog(this, "Usuário ou senha incorretos!", "Erro", JOptionPane.ERROR_MESSAGE);
            senhaEntry.setText("");
        }
    }//GEN-LAST:event_jButton1ActionPerformed
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPasswordField senhaEntry;
    private javax.swing.JTextField usuarioEntry;
    // End of variables declaration//GEN-END:variables
}
